production:
  clients:
    default:
      uri: mongodb+srv://arthursiqueiras:plastichearts2020@cluster0.6oz7j.mongodb.net/<dbname>?retryWrites=true&w=majority

development:
  options:
    # raise_not_found_error: false
  clients:
    default:
      database: portfolio_dev
      hosts:
        - localhost:27017

test:
    default:
      database: portfolio_test
      hosts:
        - localhost:27017